# Generated by Django 5.0.7 on 2024-07-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='resume_tr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
