# Generated by Django 5.0.7 on 2024-07-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_article_resume_tr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
