# Generated by Django 5.0.7 on 2024-07-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_scientifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('resume_tr', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
